name: deploy

on:
   push:
        branches:
         - "main"
jobs:
     build:
           runs-on: ubuntu-latest
           steps:
           -
             name: Checkout
             uses: actions/checkout@v4
           -
             name: Login to Docker hub
             uses: docker/login-action@v3
             with: 
                  username: ${{ secrets.DOCKER_NAME }}
                  password: ${{ secrets.DOCKER }}
           -
             name: Set up Do ker Buildx
             uses: docker/setup-buildx-action@v3
           -
             name: Build an Push
             uses: docker/build-push/action@v5
             with: 
               context: .
               file: ./dockerFile
               push: true
               tags: docker-ecommerce:latest
                  
             





